services:
  postgres:
    image: postgres:latest
    container_name: dev_postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: naoFaltei
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"
