import { auth } from "@/auth";

import { NavBar } from "@/src/components/Navbar/Navbar";
import { Unauthorized } from "@/src/components/Unauthorized";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session || !session.user) return <Unauthorized />;
  return (
    <div>
      <NavBar />
      {children}
    </div>
  );
}
