import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { ToastProvider } from "@heroui/toast";
import { SessionProvider } from "next-auth/react";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head suppressHydrationWarning>
        <Script
          async
          src={process.env.NEXT_PUBLIC_ADSENSE_LINK}
          crossOrigin="anonymous"
        />
      </head>
      <body className={``}>
        <SessionProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <ToastProvider placement="top-right" />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
